server:
    address: 0.0.0.0
    port: 13099

stream:
    codec: mjpeg
    pixfmt: YUVJ422
    width: 1280
    height: 720
    framerate: 30

recorder:
    codec: h264_v4l2m2m
    pixfmt: YUV420
    format: mp4
    maxRecordingTimeInSeconds: 600
    width: 1280
    height: 720
    bitrate: 8000000

encodedstream:
    codec: h264_v4l2m2m
    pixfmt: YUV420
    format: mpegts
    width: 960
    height: 540
    bitrate: 8000000
