server:
    address: 0.0.0.0
    port: 13099

capturer:
    codec: mjpeg_qsv
    pixfmt: NV12
    width: 1280
    height: 720
    framerate: 30

recorder:
    codec: h264_qsv
    pixfmt: NV12
    format: mp4
    width: 1280
    height: 720
    bitrate: 2000000
    maxRecordingTimeInSeconds: 600

encoder:
    codec: h264_qsv
    pixfmt: NV12
    format: mpegts
    width: 1280
    height: 720
    bitrate: 2000000